## Pooled Sample Weighting ##
## All Formats ##

## Translated directly from SAS

# Crime Area
crime_area <- c(
  `-4` = "Other missing - in area less than 2 years",
  `-1` = "Don't know / Refused",
  `1` = "A lot more",
  `2` = "A little more",
  `3` = "About the same",
  `4` = "A little less",
  `5` = "A lot less")


# Police Confidence
PolCon <- c(
  `-1` = "Don't know / Refused",
  `1` = "Very confident",
  `2` = "Fairly confident",
  `3` = "Not very confident",
  `4` = "Not at all confident")


# Household Type
HType <- c(-1="Missing",
           1="1 adult male",
           2="1 adult female",
           3="2 adults",
           4="1 adult, 1 child",
           5="1 adult, 2+ children",
           6="2+ adult, 1+ children",
           7="3+ person all adult")

#Household Type 2a
HType2a <- c(-1="Missing",
             1="Single Adult",
             2="Small Adult",
             3="Large Adult",
             4="Single Parent",
             5="Small Family",
             6="Large Family",
             7="Single Pensioner",
             8="Older Couple")

# Care Provision
HH_Care <- c(	-1="Don't know - refused",
              1="Yes, provide care",
              2="No")

# Cars
cars <- c(99="none",
          1="1 Car",
          2="2 Cars",
          3="3 or more Cars",
          -1="Missing/DK/Ref")

# New Tenure
NewTenure <- c(-1="Missing/DK/Ref",
               1="Buying with the help of a mortgage or loan",
               2="Own outright (i.e. no mortgage or loan)",
               3="Pay part rent and part mortgage (shared ownership)",
               4="Renting (including in receipt of housing benefit)",
               5="Living here rent free")

# Outten
outten <- c(-1="Missing/DK/Ref",
            1="Owned outright",
            2="Mortgaged",
            3="Social Rented",
            4="PRS",
            5="Unknown rented")

# Household Income
hh_income <- c(	-1="Don't know or Refused",
                1="Less than £5,200",
                2="£5,200 - £10,399",
                3="£10,400 - £15,599",
                4="£15,600 - £20,799",
                5="£20,800 - £25,999",
                6="£26,000 - £36,399",
                7="£36,400 - £51,999",
                8="£52,000 - £77,999",
                9="£78,000 or more")

# General Health
GenHealth <- c(1="Very good",
               2="Good",
               3="Fair",
               4="Bad",
               5="Very Bad",
               -1="DK/refused")

# Smoking
Smoking <- c(	1="Yes",
              2="No",
              -1="DK/refused")

# Long-term Condition
new_ill <- c(	1="Condition and limits a little or lots",
              2="No condition/condition that doesn't limit",
              -1="DK/refused/NA")

# Sexual Identity 
SEXID <- c(9="Don't know",
           5="Refused",
           4="Other",
           3="Bisexual",
           2="Gay or Lesbian",
           1="Heterosexual or Straight",
           -1="Other missing")

# Marital Status
MaritalS <- c(-1="Don't know/Refused",
              1="Never married and never registered a same-sex civil partnership",
              2="Married",
              3="In a registered same-sex civil partnership",
              4="Separated, but still legally married",
              5="Separated, but still legally in a same-sex civil partnership",
              6="Divorced",
              7="Formerly in a same-sex civil partnership",
              8="Widowed",
              9="Surviving partner from a same-sex civil partnership")

# Employment Status
ILOEmp <- c(1="In employment",
            2="ILO unemployed",
            3="Inactive",
            4="DK/Refused")

# Top Qualification
TopQ <- c(1="Level 1 - O Grade, Standard grade or equiv (SVQ level 1 or 2)",
          2="Level 2 - Higher, A level or equivalent (SVQ Level 3)",
          3="Level 3 - HNC/HND or equivalent (SVQ Level 4)",
          4="Level 4 - Degree, Professional qualification (Above SVQ Level 4)",
          5="Other qualification",
          6="No qualifications",
          7="Qualifications not known",
          999="Other missing")

# Religion
Religion <- c(-1="Don't know/refused",
              1="None",
              2="Church of Scotland",
              3="Roman Catholic",
              4="Other Christian",
              5="Muslim",
              6="Buddhist",
              7="Sikh",
              8="Jewish",
              9="Hindu",
              10="Pagan",
              11="Another religion")

# Ethnic Group
EthnicGroup <- c(-1="Don't know / Refused",
                 1="A - WHITE - White Scottish",
                 2="A - WHITE - Other British",
                 3="A - WHITE - Irish",
                 4="A - WHITE - Gypsy/Traveller",
                 5="A - WHITE - Polish",
                 6="A - WHITE - Any other white ethnic group",
                 7="B - MIXED OR MULTIPLE ETHNIC GROUP - Any mixed or multiple ethnic groups",
                 8="C - ASIAN, ASIAN SCOTTISH OR ASIAN BRITISH - Pakistani, Pakistani Scottish or Pakistani British",
                 9="C - ASIAN, ASIAN SCOTTISH OR ASIAN BRITISH - Indian, Indian Scottish or Indian British",
                 10="C - ASIAN, ASIAN SCOTTISH OR ASIAN BRITISH - Bangladeshi, Bangladeshi Scottish or Bangladeshi British",
                 11="C - ASIAN, ASIAN SCOTTISH OR ASIAN BRITISH - Chinese, Chinese Scottish or Chinese British",
                 12="C - ASIAN, ASIAN SCOTTISH OR ASIAN BRITISH - Other Asian, Asian Scottish or Asian British",
                 13="D - AFRICAN - African, African Scottish or African British",
                 14="D - AFRICAN - Other African background",
                 15="E - CARIBBEAN OR BLACK - Caribbean, Caribbean Scottish or Caribbean British",
                 16="E - CARIBBEAN OR BLACK - Black, Black Scottish or Black British",
                 17="E - CARIBBEAN OR BLACK - Other Caribbean or Black background",
                 18="F - OTHER ETHNIC GROUP - Arab, Arab Scottish or Arab British",
                 19="F - OTHER ETHNIC GROUP - Other")

# Birth Country
BirthCountry <- c(0="Elsewhere",
                  4="Afghanistan",
                  8="Albania",
                  10="Antarctica",
                  12="Algeria",
                  16="East Samoa",
                  20="Andorra",
                  24="Angola",
                  28="Antigua",
                  31="Azerbaijan",
                  32="Argentina",
                  36="Australia",
                  40="Austria",
                  44="Bahamas",
                  48="Bahrain",
                  50="Bangladesh",
                  51="Armenia",
                  52="Barbados",
                  56="Belgium",
                  60="Bermuda",
                  64="Bhutan",
                  68="Bolivia",
                  70="Bosnia",
                  72="Botswana",
                  74="Bouvet Island",
                  76="Brazil",
                  84="Belize",
                  86="Chagos",
                  90="Solomon Islands",
                  92="British Virgin Islands",
                  96="Brunei",
                  100="Bulgaria",
                  108="Burundi",
                  112="Belarus",
                  116="Cambodia",
                  120="Cameroon",
                  124="Canada",
                  132="Cape Verde",
                  136="Cayman Islands",
                  140="Central African Republic",
                  144="Sri Lanka",
                  148="Chad",
                  152="Chile",
                  156="China",
                  158="Taiwan",
                  162="Christmas Island",
                  170="Colombia",
                  174="Union Of The Comoros",
                  175="Mamoudzou",
                  178="Republic Of The Congo",
                  180="Democratic Republic Of Congo",
                  184="Cook Islands",
                  191="Croatia",
                  192="Cuba",
                  203="Czech Republic",
                  204="Republic Of Benin",
                  208="Denmark",
                  214="Dominican Republic",
                  218="Galapagos Islands",
                  222="El Salvador",
                  226="Equatorial Guinea",
                  231="Ethiopia",
                  232="Eritrea",
                  233="Estonia",
                  234="Faroe Islands",
                  238="Falkland Islands",
                  239="South Georgia",
                  242="Fiji",
                  246="Finland",
                  250="France",
                  254="Guiana, French",
                  258="Tahiti",
                  260="Southern Antarctic Territories, French",
                  262="Somaliland (French)",
                  266="Gabon",
                  268="Georgia",
                  270="Gambia",
                  275="Palestine",
                  276="Germany",
                  288="Ghana",
                  292="Gibraltar",
                  296="Christmas Island (Kiribati)",
                  300="Greece",
                  304="Greenland",
                  308="South Grenadine Islands",
                  312="Guadeloupe",
                  316="Guam",
                  324="Guinea",
                  328="British Guyana",
                  332="Haiti",
                  334="Territory Of Heard Island And Mcdonald Island",
                  336="Vatican City",
                  340="Honduras",
                  344="Hong Kong",
                  348="Hungary",
                  352="Iceland",
                  356="India",
                  360="Bali",
                  364="Iran",
                  368="Iraq",
                  372="Eire",
                  373="Island Of Ireland (Not Otherwise Specified",
                  376="Israel",
                  380="Italy",
                  384="Ivory Coast",
                  388="Jamaica",
                  392="Japan",
                  398="Kazakhstan",
                  400="Jordan",
                  404="Kenya",
                  408="Democratic Peoples Republic Of Korea",
                  410="Korea, Republic Of",
                  414="Kuwait",
                  417="Kyrgyzstan",
                  418="Laos",
                  422="Lebanon",
                  426="Lesotho",
                  428="Latvia",
                  430="Liberia",
                  434="Libya",
                  438="Liechtenstein",
                  440="Lithuania",
                  442="Luxembourg",
                  446="Macau",
                  450="Madagascar",
                  454="Malawi",
                  458="Malaysia",
                  462="Maldives",
                  466="Mali",
                  470="Malta",
                  474="Martinique",
                  480="Mauritius",
                  484="Mexico",
                  492="Monaco",
                  496="Mongolia",
                  498="Moldova",
                  499="Montenegro",
                  500="Montserrat",
                  504="Morocco",
                  508="Mozambique",
                  512="Oman",
                  516="Namibia",
                  520="Nauru",
                  524="Nepal",
                  528="Netherlands",
                  530="Dutch Antilles",
                  533="Aruba",
                  548="Vanuatu",
                  554="New Zealand",
                  558="Nicaragua",
                  562="Niger",
                  566="Nigeria",
                  578="Norway",
                  581="Us Pacific Island",
                  583="Micronesia",
                  584="Bikini Atoll",
                  585="Palau",
                  586="Pakistan",
                  591="Panama",
                  598="Papua New Guinea",
                  600="Paraguay",
                  604="Peru",
                  608="Philippines",
                  612="Pitcairn Islands",
                  616="Poland",
                  620="Portugal",
                  624="Guinea-Bissau",
                  626="East Timor",
                  630="Puerto Rico",
                  634="Qatar",
                  642="Romania",
                  643="Russia",
                  646="Rwanda",
                  654="Ascension Island",
                  659="Federation Of Saint Kitts And Nevis",
                  660="Anguilla",
                  662="St Lucia",
                  663="Saint Martin",
                  666="Territorial Collectivity Of Saint Pierre",
                  670="St Vincent",
                  674="San Marino",
                  678="Sao Tome",
                  682="Saudi Arabia",
                  688="Serbia",
                  690="Republic Of Seychelles",
                  694="Sierra Leone",
                  702="Singapore",
                  703="Slovakia",
                  704="Vietnam",
                  705="Slovenia",
                  706="Somali",
                  710="South Africa",
                  716="Zimbabwe",
                  732="Western Sahara",
                  736="Sudan",
                  740="Surinam",
                  744="Spitsbergen",
                  748="Swaziland",
                  752="Sweden",
                  756="Swiss Confederation",
                  760="Syria",
                  762="Tajikistan",
                  764="Thailand",
                  768="Togo",
                  776="Kingdom Of Tonga",
                  780="Trinidad And Tobago",
                  784="Dubai",
                  788="Tunisia",
                  792="Turkey",
                  795="Turkmenistan",
                  796="Turks And Caicos Islands",
                  800="Uganda",
                  804="Ukraine",
                  807="Former Yugoslav Republic Of Macedonia, T",
                  818="Egypt",
                  831="Guernsey",
                  832="Jersey",
                  833="Isle Of Man",
                  834="Tanzania",
                  840="United States Of America",
                  850="Virgin Islands (USA)",
                  854="Burkina Faso",
                  858="Uruguay",
                  860="Uzbekistan",
                  862="Venezuela",
                  876="Wallis And Futuna Islands",
                  882="Samoa",
                  887="Yemen",
                  894="Zambia",
                  901="Republic Of Cyprus",
                  902="Turkish Cyprus",
                  903="Cyprus (Not Otherwise Specified)",
                  913="Spain",
                  921="England",
                  922="Northern Ireland",
                  923="Scotland",
                  924="Wales",
                  925="Great Britain",
                  926="United Kingdom Of Great Britain And Northern Ireland",
                  931="Channel Islands",
                  951="Kosovo",
                  971="Former Czechoslovakia",
                  972="Former USSR",
                  973="Former Yugoslavia",
                  974="Serbia And Montenegro",
                  981="Europe (Not Otherwise Specified)",
                  982="Africa",
                  983="Kurdistan",
                  984="Asia",
                  985="North America (Not Otherwise Specified)",
                  987="South America",
                  988="West Indies",
                  989="Australasia",
                  999="Refused",
                  1001="SHS Missing",
                  -1="DK or NA")


# Summary of Birth Country
SummaryBirthCountry <- c(0-371="Other",
                         372="Republic of Ireland",
                         373-920="Other",
                         921="England",
                         922="Northern Ireland",
                         923="Scotland",
                         924="Wales",
                         925-998="Other",
                         999="Refused",
                         1001="SHS Missing",
                         -1="DK or NA")

#Sex
Sex <- c(1="Male",
         2="Female")

# Health Board
HealthBoard <- c(1="Ayrshire & Arran",
                 2="Borders",
                 3="Dumfries and Galloway",
                 4="Fife",
                 5="Forth Valley",
                 6="Grampian",
                 7="Greater Glasgow & Clyde",
                 8="Highland",
                 9="Lanarkshire",
                 10="Lothian",
                 11="Orkney",
                 12="Shetland",
                 13="Tayside",
                 14="Western Isles")


# Age Group
ageG <- c(1="16-24",
          2="25-34",
          3="35-44",
          4="45-54",
          5="55-64",
          6="65-74",
          7="75+")


# Urban-Rural Code
UrbRurCode <- c(1="Large Urban Area",
                2="Other Urban Area",
                3="Accessible Small Town",
                4="Remote Small Town",
                5="Accessible Rural",
                6="Remote Rural")